name: mtg
description: "A Magic: The Gathering, Scryfall, and Utility package for making, and using, MTG apps."
version: 1.0.2+2
repository: https://github.com/ArcaneArts/mtg
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
#dependency_overrides:
#  magic_card:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/magic_card/"
#  nonsense_foil:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/nonsense-foil"

dependencies:
  flutter_svg: <=2.0.17
  scryfall_api: <=2.2.0
  fast_log: <=1.0.7
  cached_network_image: <=3.4.1

  flutter:
    sdk: flutter
  serviced: ^1.0.3
  magic_card: <=2.0.0
  nonsense_foil: ^0.9.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/
