name: mtg
description: "A Magic: The Gathering, Scryfall, and Utility package for making, and using, MTG apps."
version: 1.0.3+1
repository: https://github.com/ArcaneArts/mtg
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
#dependency_overrides:
#  magic_card:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/magic_card/"
#  nonsense_foil:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/nonsense-foil"

dependencies:
  flutter_svg: any
  scryfall_api: any
  fast_log: any
  cached_network_image: ^3.4.1

  flutter:
    sdk: flutter
  serviced: ^1.0.3
  magic_card: ^1.3.0
  nonsense_foil: ^0.9.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  assets:
    - assets/magic/
