name: mtg
description: "A Magic: The Gathering, Scryfall, and Utility package for making, and using, MTG apps."
version: 1.0.3
repository: https://github.com/ArcaneArts/mtg
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
#dependency_overrides:
#  magic_card:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/magic_card/"
#  nonsense_foil:
#    path: "/Users/brianfopiano/Developer/RemoteGit/ArcaneArts/nonsense-foil"

dependencies:
  flutter_svg: any
  scryfall_api: <=3.0.0
  fast_log: <=2.0.0
  cached_network_image: <=4.0.0

  flutter:
    sdk: flutter
  serviced: <=1.0.5
  magic_card: <=2.0.01
  nonsense_foil: <=2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/magic/
